_target_: src.mtr.models.mtr_module.MTRLiDARModule

defaults:
  - scheduler: warmup-lineardecay

optimizer:
  # _target_: torch.optim.AdamW
  # _partial_: true
  name: AdamW
  lr: 0.0001
  weight_decay: 0.01

# floating point precision, high gives same speed up as medium
precision: high

CONTEXT_ENCODER:
  NAME: MTREncoder

  NUM_OF_ATTN_NEIGHBORS: 16
  NUM_INPUT_ATTR_AGENT: 29
  NUM_INPUT_ATTR_MAP: 9

  NUM_CHANNEL_IN_MLP_AGENT: 256
  NUM_CHANNEL_IN_MLP_MAP: 64
  NUM_LAYER_IN_MLP_AGENT: 3
  NUM_LAYER_IN_MLP_MAP: 5
  NUM_LAYER_IN_PRE_MLP_MAP: 3

  D_MODEL: 256
  NUM_ATTN_LAYERS: 6
  NUM_ATTN_HEAD: 8
  DROPOUT_OF_ATTN: 0.1

  USE_LOCAL_ATTN: True

MOTION_DECODER:
  NAME: MTRDecoder

  CENTER_OFFSET_OF_MAP: ${data.CENTER_OFFSET_OF_MAP}
  OBJECT_TYPE: ${subset.object_types}

  NUM_FUTURE_FRAMES: 80
  NUM_MOTION_MODES: 6

  INTENTION_POINTS_FILE: ${paths.root_dir}/data/waymo/cluster_64_center_dict.pkl

  D_MODEL: 512
  NUM_DECODER_LAYERS: 6
  NUM_ATTN_HEAD: 8
  MAP_D_MODEL: 256
  DROPOUT_OF_ATTN: 0.1

  NUM_BASE_MAP_POLYLINES: 256
  NUM_WAYPOINT_MAP_POLYLINES: 128

  LOSS_WEIGHTS:
    cls: 50.0 # to account for normalizing
    red: 1.0
    vel: 0.5

  NMS_DIST_THRESH: 2.5
