progress_bar:
  _target_: lightning.pytorch.callbacks.RichProgressBar

model_summary:
  _target_: lightning.pytorch.callbacks.RichModelSummary
  max_depth: 2 # the maximum depth of layer nesting that the summary will include

learning_rate_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: step
