# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: standard
  - model: standard
  - subset: all_types
  - paths: default
  - extras: default
  - hydra: default
  - callbacks: default
  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null

  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: null

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

  - optional validation: null

# task name, determines output directory path
task_name: "nms_search"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
tags: ["nms_search"]

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: null

num_batches: 2000
# train or test dataloader to check for
data_loader: test
